"""M8 - Farm risk engine plus the weather context providers it consumes."""

from backend.risk.engine import RiskAssessment, RiskEngine, RiskInput
from backend.risk.rules import (
    CODE_CANOPY_ANOMALY,
    CODE_FAIR_HEALTH,
    CODE_HEAT_STRESS,
    CODE_HEAVY_RAIN,
    CODE_LOSS_PRESSURE,
    CODE_LOW_CONFIDENCE,
    CODE_LOW_SOIL_MOISTURE,
    CODE_NO_IMAGE_EVIDENCE,
    CODE_POOR_HEALTH,
    CODE_POSSIBLE_DISEASE,
    CODE_RAIN,
    CODE_STRONG_WIND,
    CONFIRMATION_NOTE,
    RISK_HIGH,
    RISK_LOW,
    RISK_MEDIUM,
    RISK_NONE,
)
from backend.risk.weather import (
    STATE_FORECAST,
    build_weather_provider,
    STATE_UNAVAILABLE,
    GoogleWeatherProvider,
    OpenMeteoWeatherProvider,
    SeededWeatherProvider,
    WeatherContext,
    WeatherEvent,
    WeatherProvider,
    unavailable,
)

__all__ = [
    "CODE_CANOPY_ANOMALY",
    "CODE_FAIR_HEALTH",
    "CODE_HEAT_STRESS",
    "CODE_HEAVY_RAIN",
    "CODE_LOSS_PRESSURE",
    "CODE_LOW_CONFIDENCE",
    "CODE_LOW_SOIL_MOISTURE",
    "CODE_NO_IMAGE_EVIDENCE",
    "CODE_POOR_HEALTH",
    "CODE_POSSIBLE_DISEASE",
    "CODE_RAIN",
    "CODE_STRONG_WIND",
    "CONFIRMATION_NOTE",
    "GoogleWeatherProvider",
    "OpenMeteoWeatherProvider",
    "RISK_HIGH",
    "RISK_LOW",
    "RISK_MEDIUM",
    "RISK_NONE",
    "RiskAssessment",
    "RiskEngine",
    "RiskInput",
    "STATE_FORECAST",
    "STATE_UNAVAILABLE",
    "SeededWeatherProvider",
    "WeatherContext",
    "WeatherEvent",
    "WeatherProvider",
    "build_weather_provider",
    "unavailable",
]
