/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#ecf6ef",
        "on-tertiary": "#ffffff",
        "primary-container": "#183c32",
        "on-surface-variant": "#414845",
        "on-error-container": "#93000a",
        "inverse-primary": "#a8cfc1",
        "outline": "#717975",
        "on-primary-container": "#81a799",
        "tertiary-fixed": "#ffdbce",
        "background": "#f2fcf5",
        "surface-variant": "#dbe5de",
        "on-primary-fixed": "#002018",
        "outline-variant": "#c1c8c4",
        "primary": "#00261d",
        "surface-dim": "#d2dcd6",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#dc8a69",
        "primary-fixed": "#c4ebdc",
        "on-error": "#ffffff",
        "secondary": "#4d6452",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#370e00",
        "on-secondary-fixed-variant": "#364c3c",
        "on-primary-fixed-variant": "#2a4d43",
        "inverse-on-surface": "#e9f3ed",
        "secondary-fixed-dim": "#b4cdb8",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#a8cfc1",
        "surface-tint": "#42655a",
        "secondary-fixed": "#d0e9d3",
        "on-tertiary-fixed-variant": "#72351b",
        "tertiary-fixed-dim": "#ffb598",
        "on-secondary-fixed": "#0b2012",
        "surface-container-highest": "#dbe5de",
        "error-container": "#ffdad6",
        "on-surface": "#151d1a",
        "tertiary": "#3f1200",
        "surface-container-high": "#e1ebe4",
        "surface-container": "#e6f0ea",
        "surface-container-lowest": "#ffffff",
        "surface": "#f2fcf5",
        "on-secondary-container": "#526856",
        "on-background": "#151d1a",
        "tertiary-container": "#5d250b",
        "inverse-surface": "#29322e",
        "secondary-container": "#cde6d0",
        "surface-bright": "#f2fcf5"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-tablet": "1.5rem",
        "gutter-desktop": "1.5rem",
        "space-2xl": "3.5rem",
        "space-xl": "2.25rem",
        "space-lg": "1.5rem",
        "space-xs": "0.25rem",
        "gutter": "1rem",
        "space-md": "1rem",
        "margin": "1rem",
        "space-sm": "0.5rem",
        "margin-desktop": "2.5rem"
      },
      fontFamily: {
        "technical-label": ["IBM Plex Sans"],
        "page-title": ["IBM Plex Sans"],
        "body-default": ["IBM Plex Sans"],
        "display": ["IBM Plex Sans"],
        "display-mobile": ["IBM Plex Sans"],
        "body-emphasis": ["IBM Plex Sans"],
        "metric-value": ["IBM Plex Sans"],
        "page-title-mobile": ["IBM Plex Sans"],
        "body-secondary": ["IBM Plex Sans"],
        "section-title": ["IBM Plex Sans"]
      },
      fontSize: {
        "technical-label": ["11px", { "lineHeight": "16px", "letterSpacing": "0.08em", "fontWeight": "500" }],
        "page-title": ["30px", { "lineHeight": "38px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-default": ["15px", { "lineHeight": "22px", "letterSpacing": "0em", "fontWeight": "400" }],
        "display": ["52px", { "lineHeight": "60px", "letterSpacing": "-0.02em", "fontWeight": "500" }],
        "display-mobile": ["36px", { "lineHeight": "42px", "letterSpacing": "-0.01em", "fontWeight": "500" }],
        "body-emphasis": ["15px", { "lineHeight": "22px", "letterSpacing": "0em", "fontWeight": "600" }],
        "metric-value": ["28px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "500" }],
        "page-title-mobile": ["24px", { "lineHeight": "32px", "letterSpacing": "0em", "fontWeight": "600" }],
        "body-secondary": ["13px", { "lineHeight": "18px", "letterSpacing": "0em", "fontWeight": "400" }],
        "section-title": ["19px", { "lineHeight": "26px", "letterSpacing": "0em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
